### ISSUE TITLE
Bug when running npm run lint on Windows machine

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/tools-dashboard#53]
When running `npm run format` on Window machine, I get the following error:

```
$ npm run format

> @freecodecamp/contribute@ format D:\Coding\github-tools
> prettier --write es5 './**/*.{js,json}' && npm run lint

[error] No matching files. Patterns tried: es5 './**/*.{js,json}' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @freecodecamp/contribute@ format: `prettier --write es5 './**/*.{js,json}' && npm run lint`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @freecodecamp/contribute@ format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OPT\AppData\Roaming\npm-cache\_logs\2019-01-06T08_13_20_368Z-debug.log
```

Not sure how to proceed.

**Comment by RandellDawson** [comment]
@Nirajn2311, @lynxlynxlynx .  After updating my local with PR #55, I tried to run `npm run format` and now I get a new error:
```
> @freecodecamp/contribute@ lint D:\Coding\github-tools
> eslint ./**/*.js --fix

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
Error: Cannot find module '@ljharb/eslint-config'
Referenced from: D:\Coding\github-tools\lib\node_modules\extend\.eslintrc
    at ModuleResolver.resolve (D:\Coding\github-tools\node_modules\eslint\lib\util\module-resolver.js:72:19)
    at resolve (D:\Coding\github-tools\node_modules\eslint\lib\config\config-file.js:484:28)
    at load (D:\Coding\github-tools\node_modules\eslint\lib\config\config-file.js:556:26)
    at configExtends.reduceRight (D:\Coding\github-tools\node_modules\eslint\lib\config\config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (D:\Coding\github-tools\node_modules\eslint\lib\config\config-file.js:408:26)
    at loadFromDisk (D:\Coding\github-tools\node_modules\eslint\lib\config\config-file.js:528:22)
    at Object.load (D:\Coding\github-tools\node_modules\eslint\lib\config\config-file.js:564:20)
    at Config.getLocalConfigHierarchy (D:\Coding\github-tools\node_modules\eslint\lib\config.js:240:44)
    at Config.getConfigHierarchy (D:\Coding\github-tools\node_modules\eslint\lib\config.js:192:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @freecodecamp/contribute@ lint: `eslint ./**/*.js --fix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @freecodecamp/contribute@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OPT\AppData\Roaming\npm-cache\_logs\2019-01-06T21_35_42_693Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @freecodecamp/contribute@ format: `prettier --write es5 ./**/*.{js,json} && npm run lint`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @freecodecamp/contribute@ format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OPT\AppData\Roaming\npm-cache\_logs\2019-01-06T21_35_42_724Z-debug.log
```
So you both were able to run the command on a Windows machine without getting any errors?

cc/@raisedadead,

**Comment by Nirajn2311** [comment]
@RandellDawson this is a problem related to the next command in the format script ie. the lint script. I am looking into this.

**Comment by Nirajn2311** [comment]
@RandellDawson Update - So I was able to resolve the above issue regarding the eslint-config, but another problem regarding CRA and eslint has popped up. Also is ESLint necessary?

**Comment by RandellDawson** [comment]
I have updated the title of this PR to reflect it is the `npm run lint` part of `npm run format` and not the `prettier` functionality.

**Comment by Nirajn2311** [comment]
**UPDATE** - I was able to bypass the above issue by creating a `.eslintignore` file and putting `node_modules` in it. For some reason ESLint was also going through node_modules which shouldn't happen.

But the next error I get is -
```
> @freecodecamp/contribute@ lint C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools
> eslint ./**/*.js --fix

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
Error: Cannot find module 'eslint-config-react-app'
Referenced from: C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\probot\client\package.json
    at ModuleResolver.resolve (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\util\module-resolver.js:72:19)
    at resolve (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config\config-file.js:484:28)
    at load (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config\config-file.js:556:26)
    at configExtends.reduceRight (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config\config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config\config-file.js:408:26)    at loadFromDisk (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config\config-file.js:528:22)    at Object.load (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config\config-file.js:564:20)
    at Config.getLocalConfigHierarchy (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config.js:240:44)
    at Config.getConfigHierarchy (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\github-tools\node_modules\eslint\lib\config.js:192:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @freecodecamp/contribute@ lint: `eslint ./**/*.js --fix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @freecodecamp/contribute@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nandish\AppData\Roaming\npm-cache\_logs\2019-01-08T09_32_21_184Z-debug.log
```

The strange thing is all the required ESLint modules for React and CRA are present and yet the issue appears. I need help with this as I haven't learnt React and know only Vue at the moment.

cc - @RandellDawson @raisedadead
